// flow-typed signature: f5eb05e02332e3e90e6e704ef5be51c6
// flow-typed version: <<STUB>>/postcss-conditionals_v^2.1.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-conditionals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-conditionals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-conditionals/parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-conditionals/index' {
  declare module.exports: $Exports<'postcss-conditionals'>;
}
declare module 'postcss-conditionals/index.js' {
  declare module.exports: $Exports<'postcss-conditionals'>;
}
declare module 'postcss-conditionals/parser.js' {
  declare module.exports: $Exports<'postcss-conditionals/parser'>;
}
