// flow-typed signature: bd487b69c5c2a41d83cf94c350f3c3eb
// flow-typed version: <<STUB>>/postcss-at-rules-variables_v^0.0.26/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-at-rules-variables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-at-rules-variables' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-at-rules-variables/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-at-rules-variables/lib/index.js' {
  declare module.exports: $Exports<'postcss-at-rules-variables/lib/index'>;
}
